#pragma once

#ifndef MY_VOCA_LIST_H
#define MY_VOCA_LIST_H

#include "MyVoca.h"

int NUM_MY_TOEIC_VOCA = 100;

MyVoca myToeicVocaList[] =
{
MyVoca("convex", ADJ, { "Curved", "rounded", "arched" }, { "Sidiz is a popular brand of chair, because it makes convex cushion on the seat for comfortable state." }),
MyVoca("variance", NOUN, { "Disagreement", "variation", "conflict", "alteration" }, { "I suggest you to confirm variance of the final exam¡¯s result, because it is the indicator of your grade position." }),
MyVoca("prevalent", ADJ, { "Popular", "common", "normal", "typical" }, { "GGANG is the song of rain who is powerful singer and it is prevalent by You-tube." }),
MyVoca("cofactor", NOUN, { "Common factor", "mutual factor"  }, { "Cofactor is worked by functioning together between one material and another and makes new product from them." }),
MyVoca("congruent", ADJ, { "Suit", "matching", "harmonious", "fitting" }, { "When you make a puzzle, one tip is to find the piece that is congruent with the shape of puzzle board." }),
MyVoca("conjecture", VERB, { "Estimate", "guess", "assume" }, { "I can¡¯t stop conjecturing about someone¡¯s bad behavior, when someone did the same lie before." }),
MyVoca("conjecture", NOUN, { "Hypothesis", "theory", "assumption"  }, { "The heavy conjecture can make other wrong information in your mind and it is also bad for your metal condition." }),
MyVoca("derivative", ADJ, { "Copied", "derived"  }, { "GENESIS is the derivative brand of HYNDAI Motor and is consisted of luxury cars like G80 and GV80." }),
MyVoca("derivative", NOUN, { "Result", "product" }, { "I think that derivative is the most important and basic tool in math because it gives the variable¡¯s rate of change." }),
MyVoca("proficient", ADJ, { "skillful", "expert", "capable" }, { "Engineers are proficient at English because lots of information that they should learn is in books, papers and articles in English." }),
MyVoca("certificate", VERB, { "qualify", "entitle", "authorize" }, { "You can be certificated as teacher, if you are involved in the list announcing passed applicants" }),
MyVoca("certificate", NOUN, { "diploma", "credential", "license"  }, { "You should bring the certificate given by government, if you want to enter the center." }),
MyVoca("hesitant", ADJ, { "uncertain", "cautious", "tentative" }, { "Don¡¯t be hesitant in face to face communication because of the unrisen situations that can worsen relations." }),
MyVoca("interest", VERB, { "attract", "grip", "intrigue", "fascinate" }, { "Almost every baby is interested in movement, so that they like toys stimulating their eyes." }),
MyVoca("interest", NOUN, { "hobby", "attention", "curiosity"  }, { "I don¡¯t have any interests in computer games because they don¡¯t make me excited." }),
MyVoca("eligible", ADJ, { "qualified", "entitled"  }, { "He is eligible to vote president election in Korea as he has lived more than 20 years." }),
MyVoca("aptitude", NOUN, { "talent", "ability", "capacity" }, { "People have their own aptitude to make one¡¯s life more meaningful and richer although finding it is hard work." }),
MyVoca("present", NOUN, { "gift"  }, { "I got present box at my birthday that is composed with cosmetics, handkerchief, and one million won." }),
MyVoca("present", ADJ, { "contemporary", "existent", "current" }, { "The present situation that require social isolation by COVID-19 influences almost everything badly." }),
MyVoca("present", VERB, { "give", "award", "submit" }, { "Students should present the reports until this Friday including experiment result picture and your own ideas." }),
MyVoca("recruit", NOUN, { "trainee", "apprentice" }, { "If you had been soldier, you must have time as recruit that is short in every part." }),
MyVoca("recruit", VERB, { "employ", "hire", "engage" }, { "I want to be recruited by vehicle company particularly three big business in Germany like BMW." }),
MyVoca("resume", NOUN, { "summary", "precis", "abstract" }, { "Resume is an important part of the assertion like papers and essays to remind the topic to readers." }),
MyVoca("resume", VERB, { "recommence", "continue", "restart" }, { "Laborers should resume the work in several minutes to accomplish the today¡¯s goal for convenient weekend." }),
MyVoca("stipulate", ADJ, { "stipular", "stipellate" }, { "Can anybody here distinguish the stipulate tree in the bushy woods that place behind the IT block?  " }),
MyVoca("stipulate", VERB, { "specify", "order", "require" }, { "Rules that you have to follow in the guest house are stipulated on the black board which places at the entrance." }),
MyVoca("utility", ADJ, { "versatile", "multipurpose" }, { "In the door, there is an utility room that you can work like laundry and DIY." }),
MyVoca("utility", NOUN, { "usefulness", "practicality" }, { "When I buy an electronic device like a cell phone, first thing that I check is an utility." }),
MyVoca("deteriorate", VERB, { "worsen", "weaken"  }, { "His dog¡¯s health had been deteriorated for 2 months, finally the dog died in March. 1. 2020." }),
MyVoca("compatible", ADJ, { "companionable", "consistent" }, { "Galaxy Buds made in Samsung are a bluetooth earphones that compatible with I-phone made in Apple.  " }),
MyVoca("refrain", NOUN, { "chorus", "melody" }, { "It is extremely hard work to refrain smoking at once to long time smokers except minority." }),
MyVoca("refrain", VERB, { "cease", "abstain", "desist" }, { "It is extremely hard work to refrain smoking at once to long time smokers except minority." }),
MyVoca("cordially", ADJ, { "pleasantly", "warmly" }, { "My little niece cordially greets my family when we go to her house in national holiday." }),
MyVoca("process", NOUN, { "procedure", "course"  }, { "The process of assembling car is not that hard work but designing process is pretty hard work." }),
MyVoca("process", VERB, { "handle", "treat", "manufacture" }, { "One way that separate the grades of diamond is how many sides are processed elaborately." }),
MyVoca("succinct", ADJ, { "concise", "brief", "pithy"  }, { "Good essay should involve succinct and specific assertion and explanations for readers to understand easily. " }),
MyVoca("construct", VERB, { "build", "make" }, { "I have lived in Lotte apartment for 20 years that is constructed in 1999 year and I¡¯ll live until next year." }),
MyVoca("elaborate", ADJ, { "ornate", "precise"  }, { "The elaborate diamonds look more shining than others because they have more piece of sides." }),
MyVoca("premise", NOUN, { "proposition", "foundation", "ground"}, { "In a essay, it will be better to put premise like a background to persuade reader." }),
MyVoca("elaborate", VERB, { "amplify", "enlarge on"}, { "I elaborate to this report compared with others to get high score in English communication class." }),
MyVoca("obligate", ADJ, { "Unavoidable", "inevitable", "mandatory", "bounden", "obligate" }, { "It is obligate to Korea men to serve in a army for about 2 years except special cases." }),
MyVoca("obligate", VERB, { "Force", "pressure", "impose", "compel" }, { "When I was a third grade of student of Muhak high school, teachers obligated students to remain until PM 11:00 in name of self-studying." }),
MyVoca("resolve", ADJ, { "Resolution", "determination", "decision" }, { "She has a strong resolve that she will not marry with her boyfriend until their money problem is solved." }),
MyVoca("resolve", VERB, { "Settle", "solve"  }, { "He and his girlfriend have a meeting on this Saturday to resolve their money problem for a wedding." }),
MyVoca("adverse", ADJ, { "Harmful", "negative", "hostile", "contrary"  }, { "For psychiatric patients, adverse thinks can be critically harmful for treatment and their daily lives." }),
MyVoca("substitute", NOUN, { "Alternative", "replacement", "deputy", "proxy" }, { "Because of COVID-19, Yung Nam University has problems in opening offline class so that online class is adapted with substitute of offline class.   " }),
MyVoca("substitute", VERB, { "Replace", "swap", "switch" }, { "In a soccer game, lack of a player can substitute with other players but the absence of performance can¡¯t substitute." }),
MyVoca("specific", ADJ, { "Precise", "peculiar", "particular", "explicit"  }, { "When you are writing an essay, give specific supporting reasons about a thesis statement to facilitate the understanding for readers." }),
MyVoca("register", NOUN, { "List", "file"}, { "You should check on the register first for an exact paycheck when you here to work." }),
MyVoca("register", VERB, { "Enroll", "catalogue", "record" }, { "My mother registered SJ health club for a year but she can¡¯t go club because of social distance." }),
MyVoca("frequent", ADJ, { "Repeated", "common", "regular" }, { "Frequent smoking is harmful not only for your own health but also for others¡¯ health beside you." }),
MyVoca("frequent", VERB, { "Visit", "haunt"  }, { "She frequents to the cafe named ¡®Sounds Coffee¡¯ because of jazz style background music and dark interior. " }),
MyVoca("diverse", ADJ, { "Various"  }, { "One of my hobby is collecting diverse perfumes, especially woody scent things because of my unique taste." }),
MyVoca("prerequisite", NOUN, { "Requirement", "qualification" }, { "You have to meet a prerequisite that company requires if you want to hand in an application to big company like SAMSUNG." }),
MyVoca("prerequisite", ADJ, { "Necessary" }, { "A certificate of 850+TOEIC is prerequisite if you want to hand in an application to big company like SAMSUNG." }),
MyVoca("revenue", VERB, { "Income", "profit", "returns" }, { "Last year, our company¡¯s revenue increased about 10% compared with two years ago, and this year¡¯s goal is 20% increase compared with last year." }),
MyVoca("integral", ADJ, { "Complete", "entire", "essential", "vital"}, { "Son completely takes root in Tottenham as an integral player particularly as a left wing and one top." }),
MyVoca("integral", NOUN, { "Whole", "entirety", "all"}, { "A definite integral is used in widely in engineering, so you have to understand it exactly." }),
MyVoca("compare", VERB, { "Contrast"  }, { "I prefer SUV compared with sedan because of the high seat position and big trunk." }),
MyVoca("mandatory", ADJ, { "Necessary", "obligatory", "essential", "forced"  }, { "In South Korea, military service about 2 years is mandatory and it is one of the four duties of people. " }),
MyVoca("consistent", ADJ, { "Steady", "constant", "relevant" }, { "You have to assert consistence opinion in every paragraph when you write an essay to persuade readers." }),
MyVoca("mediate", VERB, { "Intercede", "referee", "negotiate " }, { "If he didn¡¯t mediate me when I was fighting with a stranger, I would be in the jail." }),
MyVoca("quality", ADJ, { "Luxury", "advanced", "fancy", "prestige" }, { "I want to be gifted a quality present next year which costs over one million won because I got one million won on this birthday as a present." }),
MyVoca("quality", NOUN, { "Character", "property", "quantity" }, { "These days, as customers become smart, the quality of products becomes more important than before of course in rational cost." }),
MyVoca("rectify", VERB, { "Correct", "revise" }, { "Sometimes, I want to rectify wrong relationship with my friend who became awkward after graduating the high school." }),
MyVoca("dominate", ADJ, { "Govern", "control"  }, { "In an e-sports, particularly in LOL, Faker who is mid liner of T1 usually dominate the games by his sensitive control." }),
MyVoca("endorse", VERB, { "Support", "approve" }, { "I hope my family to endorse my business that provide people a place to take a picnic indoors." }),
MyVoca("accurate", ADJ, { "Exact", "precise" }, { "Computer programming demands accurate source code because a small mistake leads program to a wrong way." }),
MyVoca("deduct", VERB, { "Subtract", "remove" }, { "Most part timers don¡¯t like deduct insurance bill from their pay, but it is helpful in the long run. " }),
MyVoca("aggressive", ADJ, { "Violent", "hostile", "destructive"  }, { "Too aggressive behavior in negotiation table can be poison for you in terms of later negotiation." }),
MyVoca("decline", NOUN, { "Decrease", "fall", "wane", "decay" }, { "Decline of a birthrate is very serious social problem, so that environments for a birth should be more improved." }),
MyVoca("decline", VERB, { "Reduce", "fall", "decrease", "decay" }, { "It looks like that population of children declines in HaYang town after I graduate the elementary school." }),
MyVoca("subsidiary", ADJ, { "Minor", "junior", "secondary" }, { "At the negotiation, don¡¯t be attracted by subsidiary conditions but concentrate on main a goal." }),
MyVoca("subsidiary", NOUN, { "Company", "firm", "affiliate"  }, { "A subsidiary is a company that is dominated by parent company that have more than 50% subsidiary¡¯s stock." }),
MyVoca("waive", VERB, { "Surrender", "abandon", "give up" }, { "It is too good suggestion to waive that working as an information security guard at DaeGu bank." }),
MyVoca("bilateral", ADJ, { "Mutual", "two-sided" }, { "Physical contact should be allowed under bilateral agreements, of course in a company and even in a home." }),
MyVoca("audit", NOUN, { "Check", "review", "inspection", "examination" }, { "Auditing is a work to discover companies that commit illegalities and corruption for healthy social." }),
MyVoca("audit", VERB, { "Check", "review", "inspect", "examine" }, { "Auditing companies for various reasons should be clearand fair to find out illegalitiesand corruption." }),
MyVoca("budget", ADJ, { "Cheap", "inexpensive", "economical", "low-priced"}, { "There are a lot of budget products in internet shopping malls which treat almost every sector, particularly in OK mall." }),
MyVoca("budget", NOUN, { "finances", "accounts"  }, { "In company, every department has to cost under their budget when pushing forward projects so that company develop efficiently." }),
MyVoca("budget", VERB, { "Plan", "account" }, { "It is important to budget before new projects for checking reasonable investment cost and following results." }),
MyVoca("apprehensive", ADJ, { "Anxious", "worried", "concerned" }, { "You don¡¯t have to be apprehensive about upcoming date for teeth treatment, rather care about upcoming test." }),
MyVoca("commodity", NOUN, { "Product", "goods", "supply" }, { "In Italy, there are less commodities in markets because people buy goods more than necessary due to COVID-19." }),
MyVoca("withdraw", VERB, { "Remove", "leave", "cancel" }, { "There are some people who assert to withdraw the United States army in Korea, but I am opposite to them." }),
MyVoca("yield", NOUN, { "Harvest", "produce", "profit", "income" }, { "Depending on the yield of whole regions in this year, price of agriculture products can increase highly or plummet." }),
MyVoca("yield", VERB, { "Produce", "generate" }, { "It is important for famers to yield their harvests in proper time for good quality and income." }),
MyVoca("tenant", NOUN, { "Occupant", "renter", "resident", "lodger"  }, { "It is basic manner to be quiet for other tenants in nighttime to not bother them." }),
MyVoca("tenant", VERB, { "Rent", "reside", "habitat" }, { "Lots of college students that have their main house far from the college tenant in one-room, paying about 300,000 won per month." }),
MyVoca("legitimate", ADJ, { "proper", "reasonable", "logical" }, { "Her family motto is ¡°Be legitimate¡± and ,when I see her real life, I think that she follows her family motto well." }),
MyVoca("weave", NOUN, { "Pile", "pattern"}, { "When I was a middle school student, weave for a cushion was a performance assessment and I got the highest grade " }),
MyVoca("weave", VERB, { "Intertwine", "interlace"  }, { "In my great grandmother¡¯s generation, women usually waited their husbands, weaving clothes in front of small light." }),
MyVoca("collaborate", VERB, { "Cooperate"  }, { "Rapper Dok2¡¯s little dream is to collaborate with Kim Bum Soo who is one of the best R&B singer in Korea." }),
MyVoca("consent", NOUN, { "Agreement", "accord", "permission" }, { "Because of COVID-19, the consent paper is essential for students to take offline class in YU." }),
MyVoca("consent", VERB, { "Agree", "permission", "approve" }, { "When I become a father, I will not consent for my wife to smoke if she is a smoker." }),
MyVoca("secure", VERB, { "Guarantee", "protect" }, { "When the bank loses my money, I can be secured till 50 million won that I deposited at the bank." }),
MyVoca("secure", ADJ, { "Safe", "assured" }, { "To be a good structure, there should be secure fences at every window and roof, including warning sign." }),
MyVoca("compromise", NOUN, { "Negotiation", "deal" }, { "For a successful negotiation to both teams, a proper compromise that leads the negotiation to win-win result should be offered." }),
MyVoca("compromise", VERB, { "Negotiate"  }, { "When I was young, I used to compromise with mom for me to playing overnight at my friend¡¯s house." }),
MyVoca("complete", ADJ, { "perfect", "whole" }, { "To be a complete soul mate with your friend, you have to open your mind before him/her." }),
MyVoca("complete", VERB, { "Finish", "accomplish", "achieve", "perfect" }, { "I complete every 7th homework if I finish the last one of English Communication subject." }),

};

#endif